name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update devcard.svg
          commit_user_name: Trịnh Minh Nhật
          commit_user_email: trinhmnhat@gmail.com
          commit_author: Trịnh Minh Nhật <trinhmnhat@gmail.com>
          branch: main
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update badges" # optional
          CREDLY_SORT: POPULAR
          NUMBER_LAST_BADGES: 5
